version: "3.8"
services:
  app:
    # build:
    #   context: .
    ports:
      - 3000:3000
    image: bioniclts/ui:1.0
    container_name: ui
    command: npm start

  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'  
    volumes:
      - db-data:/var/lib/postgresql/data
      - ~/utils/zendb.sql:/docker-entrypoint-initdb.d/zendb.sql

volumes:
  db-data: